### ISSUE TITLE
Imageprocessor parameters not working

### ISSUE THREAD

**Issue by gabador-mof** [DannerrQ/Umbraco-S3-Provider#4]
Hi! 

Thank you for developing this plugin, i've just managed to get it set up, and things are more or less working finally with S3. 

I have an issue however, where imageprocessor does not seem to be applying the required image processing when requesting the image with the parameters. 

What could be the reason for this? 

This is my security config: 
```

<?xml version="1.0" encoding="utf-8"?>
<security>
  <services>    
    <service prefix="Media/" name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
      <settings>
        <setting key="MaxBytes" value="8194304" />
        <setting key="Timeout" value="30000" />
        <setting key="Host" value="https://<bucketname>.s3-accelerate.amazonaws.com/<APIKey>/" />
      </settings>
    </service>
  </services>
</security>
```
I'm all out of ideas unfortunately. 

Thank you,
Gabor

**Comment by gabador-mof** [comment]
Additionally, I'm not sure what permissions the S3 user needs to be able to write to the bucket. Setting it up with the following policy is not enough: 

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "s3:GetBucketLocation",
            "Resource": "arn:aws:s3:::*"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:GetObject",
                "s3:DeleteObject"
            ],
            "Resource": "arn:aws:s3:::test-octopus-digital/*"
        },
        {
            "Sid": "VisualEditor2",
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketAcl"
            ],
            "Resource": "arn:aws:s3:::*"
        },
        {
            "Sid": "VisualEditor3",
            "Effect": "Allow",
            "Action": "s3:ListAllMyBuckets",
            "Resource": "*"
        }
    ]
}

But S3 Full access seems to do the trick. 

We cannot allow S3 Full for the user, so it would help if you could tell me what the required permissions should be. 

Thank you! 
Gabor

**Comment by DannerrQ** [comment]
Hi Gabor, sorry I can't look at this now (super busy!) but I'll take a look at these for you tonight. I've got this working on a couple of sites so hopefully we can work out what's going wrong here

**Comment by gabador-mof** [comment]
Thank you, any help would be appreciated!

**Comment by DannerrQ** [comment]
Hi Gabor, just having a look at your config I see you're using S3 Accelerate. I haven't had a chance to add support for this yet so I'm surprised it worked at all! Having said that, I don't think that's your problem here.

I'll start by asking you a couple of questions to clear things up a little:
1. Are you using the virtual path provider?
2. If yes, have you added the StaticFileHandler snippets from the readme to ~/Web.config and ~/Media/Web.config?

On the S3 permissions front I'm not too sure what's failing there - I would have thought those permissions would be enough. I've had a look at mine but can't see any differences that should cause it to fail. I'll have to do some testing to work out the minimum set of permissions and get back to you.

I'll be honest, the majority of the work in this package was done by the previous maintainer so my knowledge is a little patchy in some areas. If not tonight or tomorrow, I'll definitely have more time at the weekend so will brush up then and hopefully I can give you more useful information.

**Comment by gabador-mof** [comment]
Thats Very kind of you Danny. I'm using virtual paths and I've added the
static handlers to the Web config.

The accelerate stuff was added as an afterthought. I'll remove it.

Seems like imageprocessor is not doing the processing with this setup.i
will send you the other config files tomorrow. Thanks for your help!
Gabor

**Comment by gabador-mof** [comment]
Hi Danny - Did you have any luck with this?
Thank you!
Gabor

**Comment by gabador-mof** [comment]
Hi Danny - So THe current setup is: 

I have this in the web config: 

`

    <add key="BucketFileSystem:Region" value="eu-west-1" />
    <add key="BucketFileSystem:BucketName" value="#bucketname#" />
    <add key="BucketFileSystem:MediaPrefix" value="media" />
    <add key="BucketFileSystem:FormsPrefix" value="forms" />
    <add key="BucketFileSystem:BucketHostname" value="" />
    <add key="BucketFileSystem:DisableVirtualPathProvider" value="false" />`

I have this in the security config: 

`<?xml version="1.0" encoding="utf-8"?>
<security>
  <services>
    
    
    
    <service prefix="Media/" name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
      <settings>
        <setting key="MaxBytes" value="8194304" />
        <setting key="Timeout" value="30000" />
        <setting key="Host" value="https://#bucketName#.s3.eu-west-1.amazonaws.com" />
      </settings>
    </service>
  </services>
</security>`

What happens is that I can read the images from S3 - but Imageprocessor doesn't do anything to them. So it doesn't process the images, they remain the same despite changing qs parameters. 

I have the static file handlers in the web configs. 

I have tried turning off the virtual path provider (added buckethostname: http://#bucketName#.s3.eu-west-1.amazonaws.com ), but then umbraco fails to load: 

![image](https://user-images.githubusercontent.com/64405523/84504691-09bae700-acc5-11ea-8295-fca7ac62423c.png)

I'm at a bit of a loss. Even with the virtual path provider turned on, I cannot upload to S3. Standard Bucket List and bucket object put/read and delete is granted to the server/user accessing the bucket.

**Comment by gabador-mof** [comment]
Hi Danny, after some further digging, I managed to get the files uploading and downloading from S3, but imageprocessor still does not process the images. 

Imageprocessor seems to be called, as I see the ImageProcessedBy Header in the response, but the processing itself is not being done. This seems to be the last piece of the puzzle for the moment... 

Thanks! 
Gabor

**Comment by gabador-mof** [comment]
I have found the cause of the issues: 
in security config, I should have had /media at the end of the host. 
I had two media location tags in the web config, so the static file handler was not being taken into account. 
Additionally, S3 requires full public access, and for the user/machine accessing s3, you need bucket list, and read/put/delete permission on the bucket as well as readACL and putACL permissions.
